language: node_js

env:
  global:
    - PATH=$PATH:./node_modules/.bin
    - secure: uW+a9ILOBWyyu0PhcoEjyu1vvfWc1q3rQi7Rj69rLKhg1tia9zEFiLWxY3pTO6TsrgUuH+SD1zzElVppV3kkbwL1FQ4lgACOB+p76y+c2VD+A7StLgNkWnoUSy7YRyMCZRg/7DUsw+oLOvQcUfubZqdLKRLfJca4ebfGD5utc8cfVO7HjqhFN/teFJ/7LDyTNsbpAi0oOzH0UNMyyREoi+o/Qgfqv5ByLPiiJA2bKvxBQs1CeiN4qWPWR21LDrEehLLnZZ7c/5wMh15LlYBPdxGn2pSK+0Yy9V6YrX0YQkqaXLMyOvlp53VfDlWj8LyRV0JZZoVewh9RXxPCbyvKKQ==



branches:
  except:
    - gh-pages

build:
  pre_ci_boot:
    image_name: drydock/u16nodall
    image_tag: v7.2.4

  ci:
    - nvm use 10
    - npm config set -g audit false
    #
    # Lint and build examples
    - cd examples
    - npm ci --ignore-scripts
    - npm run lint
    - npm run build-all
    - cd -
    #
    # Lint and build Angular Universal Node example
    - cd examples-standalone/angular-universal/node_sample_application
    - npm ci --ignore-scripts
    - npm run lint
    - npm run build
    - cd -
    #
    # Lint ASP.NET Core client app
    - cd examples-standalone/aspnetcore-data/ClientApp
    - npm ci --ignore-scripts
    - npm run lint
    - npm run build
    - cd -
    - ssh-add $SHIPPABLEKENDOANGULARPUSH_PRIVATE_KEY_PATH
    - git remote set-url origin git@github.com:telerik/kendo-angular.git
    - cd examples && ./bin/publish-gh-pages
resources:
  - name: shippable-kendo-angular-push
    type: integration
    integration: shippable-kendo-angular
jobs:
  - name: kendo-angular_runCI
    type: runCI
    steps:
      - IN: shippable-kendo-angular-push

