# Builds and publishes examples to GH pages
name: CD

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./examples

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Activate Kendo UI license
        run: npx kendo-ui-license activate
        env:
          KENDO_UI_LICENSE: ${{ secrets.KENDO_UI_LICENSE }}

      - name: Lint examples
        run: npm run lint

      - name: Build examples
        run: |
          npm run lint
          npm run build-all

      - name: Publish to GH Pages
        run: ./bin/publish-gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Cleanup
        run: git clean -xdf

