# Builds and publishes examples to GH pages
name: CD

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./examples

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required by Akeyless
      contents: read
      packages: read

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: '{ "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN" }'
          export-secrets-to-environment: false

      - name: Use NodeJS v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Build
        run: ./bin/build-gh-pages
        env:
          KENDO_UI_LICENSE: ${{ secrets.KENDO_UI_LICENSE }}

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ steps.import-secrets.outputs.GH_TOKEN }}
          publish_dir: ./examples/dist
          user_name: 'kendo-bot'
          user_email: 'kendouiteam@progress.com'

      - name: Cleanup
        run: git clean -xdf

